//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lokate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public int AdminID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string Admin_Name { get; set; }
        public string Admin_Surname { get; set; }
        public string Admin_Email { get; set; }
        public string Admin_Phone { get; set; }
        public string Admin_Password { get; set; }
        public string Admin_Status { get; set; }
    }
}
